name = "Wynncraft 101"
author = "aninuscsalas"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c781eea2746c6d54f19af2449e31193cb0bda4cfbfc55d3af3c9bfccf7aa3966"

[versions]
minecraft = "1.20.2"
quilt = "0.25.0"
