name = "Wynncraft 101"
author = "aninuscsalas"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "177bf04e3523e6f664bc2585a52e105fb0fc3d1b5f28b5d80e89ca3c2e4d09d9"

[versions]
minecraft = "1.20.2"
quilt = "0.26.0"
