name = "Wynncraft 101"
author = "aninuscsalas"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00c2ee61db27e17980ccf65c904560642e5f523883eb6c553833c387f20886e0"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
