name = "Wynncraft 101"
author = "aninuscsalas"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b0f15453c3ac01d7c60b7dd81a60d299c64347bba1ce59cfe2b318d84b775e9"

[versions]
minecraft = "1.20.2"
quilt = "0.21.2"
