name = "Wynncraft 101"
author = "aninuscsalas"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f1fc882138fbed09f1e9c98355b15d2c741e690abec465fda02d6b7262b22cb"

[versions]
minecraft = "1.20.2"
quilt = "0.23.0"
