name = "Wynncraft 101"
author = "aninuscsalas"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be89aa7de7589ced0c779a544374c331bc26e02f857f93a51d4eac709efcf6d6"

[versions]
minecraft = "1.20.2"
quilt = "0.21.1"
