name = "Wynncraft 101"
author = "aninuscsalas"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e73204e90ce9739058ab95ab9173f8cd0d7838916a0ee42e976fe4baea6a6106"

[versions]
minecraft = "1.20.2"
quilt = "0.24.0"
