name = "Wynncraft 101"
author = "aninuscsalas"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8f75157315461ed521ea3b94e1a71dd190a14c73880344e9b77318d030b5b34"

[versions]
minecraft = "1.20.2"
quilt = "0.23.0"
