name = "Wynncraft 101"
author = "aninuscsalas"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dac684df81c212f46deed486f6cf18f4671877d7cfb2a116d7bbf2690bd63500"

[versions]
minecraft = "1.20.2"
quilt = "0.22.1-beta.4"
